### ISSUE TITLE
SemVer

### ISSUE THREAD

**Issue by chrisvanpatten** [UserScape/php-customerio#19]
Would you consider re-tagging 1.0.4 as 2.0.0?

From a semver perspective, minor and patch releases (`1.*.*`) should only provide non-breaking fixes.

Because the Guzzle 6 change in #18 will break back-compat with PHP 5.3 and 5.4, semver would require a bump in the major version `2.0.0` (patch and minor releases, e.g. 1.0.4 or 1.1.0, must maintain backcompat with the major version).

The git commands to remove 1.0.4 and retag as 2.0.0:

`git tag -d 1.0.4 && git push origin :refs/tags/1.0.4 && git tag -a 2.0.0 -m "2.0.0" && git push --tags`

Just want to avoid folks who get caught off-guard, if they're doing `1.*` or `~1.0` in their composer.json files and expect no breaking changes.

**Comment by tannerhearne** [comment]
Wowow, we just encountered a major problem because of this update.  All of our customers started getting added to segments in Customer.io because of the way Guzzle handles booleans.  Instead of "1" and "null", attributes started being sent to Customer.io as "true" and "false"

@fideloper - would you consider @chrisvanpatten's suggestion about releasing this as 2.0.0?  This was a pretty severe consequence of us tracking with the 1.0.x releases.

**Comment by JonoB** [comment]
Just adding my voice to this as well. Holy crap, this was a bit nasty.

**Comment by fideloper** [comment]
1.0.4 is now gone in favor  of 2.0.0!

Apologies for that!
